#生产环境
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.100.173.47:3306/blog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#日志配置
logging:
  level:
    root: warn
    com.ffy: info
#文件输出地址
  file:
    path: log/blog-pro.log
#端口指定
server:
  port: 8888
